name: deploy

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0.2'
          bundler-cache: false  # Disable Bundler caching to avoid potential issues

      - name: Install Bundler
        run: gem install bundler

      - name: Ensure Clean Environment
        run: |
          rm -rf ./vendor/bundle
          bundle clean --force

      - name: Install Dependencies
        run: |
          bundle install --path vendor/bundle
          npm install -g mermaid.cli

      - name: Ensure Correct Gem Versions
        run: |
          bundle exec gem list
          bundle exec gem install uri -v '1.0.3'

      - name: Verify Jekyll Installation
        run: bundle exec jekyll -v

      - name: Build Site
        run: bundle exec jekyll build

      - name: Setup Deploy Options
        id: setup
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          if [[ ${GITHUB_REF} = refs/pull/*/merge ]]; then
            echo "SRC_BRANCH=${GITHUB_HEAD_REF}" >> $GITHUB_OUTPUT
            echo "NO_PUSH=--no-push" >> $GITHUB_OUTPUT
          elif [[ ${GITHUB_REF} = refs/heads/* ]]; then
            echo "SRC_BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT
          fi
          echo "DEPLOY_BRANCH=gh-pages" >> $GITHUB_OUTPUT

      - name: Deploy Website 
        run: |
          yes | bash bin/deploy --verbose ${{ steps.setup.outputs.NO_PUSH }} \
                      --src ${{ steps.setup.outputs.SRC_BRANCH }} \
                      --deploy ${{ steps.setup.outputs.DEPLOY_BRANCH }}
