name: Deploy Website

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Ruby Environment
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.0'
          bundler: '2.3.0'
          bundler-cache: false

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y imagemagick
          gem install bundler
          bundle install
          npm install -g mermaid.cli

      - name: Patch Jekyll Scholar Plugin
        run: |
          sed -i 's/File.exists?/File.exist?/g' $(bundle show jekyll-scholar)/lib/jekyll/scholar/utilities.rb

      - name: Verify Jekyll Installation
        run: bundle exec jekyll -v

      - name: Build Jekyll Site
        run: bundle exec jekyll build

      - name: Deploy Website
        run: |
          yes | bash bin/deploy --verbose
