name: Deploy Website

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Ruby Environment
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.0'  # Ensure this matches your Gemfile
          bundler-version: '2.3.0'  # Specify the Bundler version from your Gemfile.lock
          bundler-cache: true   # Enable Bundler caching

      - name: Cache Ruby Gems
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-ruby-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-ruby-

      - name: Install Dependencies
        run: |
          bundle install
          npm install -g mermaid.cli

      - name: Verify Jekyll Installation
        run: bundle exec jekyll -v

      - name: Build Jekyll Site
        run: bundle exec jekyll build

      - name: Deploy Website
        run: |
          yes | bash bin/deploy --verbose
